name: Run Unit Tests
on:
  push:
    branches:
      - main
      - working
      - working-refactor
      - workingTest
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
